### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by rusinikita** [rusinikita/devex#1]
I have a plans to add [goreleaser](https://github.com/goreleaser/goreleaser) later.

If you want to use the CLI and don't want to build it yourself, please write a comment and mention me.

**Comment by jerrdasur** [comment]
I would like to use it as a CLI for experiments.
Also, it would be great to distribute it via Homebrew and some linux package lists (snap, apt, etc.). Because this tool isn't Go specific by design.

**Comment by rusinikita** [comment]
@jerrdasur Hi! I just finished to setup goreleaser. That was long task. Sorry about that.

You can find brew install insttructions in [readme](https://github.com/rusinikita/devex/tree/main#brew-mac-os)
